import type { Metadata } from "next";
import "./globals.css";
import Navbar from '../components/own/Navbar'
import Logo from '../components/own/Logo'
import Menuprincipal from '../components/own/Menuprincipal'
import { Separator } from "@/components/ui/separator"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className=""
      >
        <Menuprincipal/>
        <Separator orientation="horizontal" className="m-0" />
        {children}
      </body>
    </html>
  );
}
